package com.example.workflow.mapper;

import com.example.workflow.dto.StockPoDetailDto;
import com.example.workflow.model.StockPoDetail;
import org.springframework.stereotype.Component;

@Component
public class StockPoDetailMapper {

    public StockPoDetailDto toDto(StockPoDetail stockPoDetail) {
        StockPoDetailDto dto = new StockPoDetailDto();
        dto.setStockPoDetailId(stockPoDetail.getStockPoDetailId());
        dto.setStockPoId(stockPoDetail.getStockPoId());
        dto.setItemId(stockPoDetail.getItemId());
        dto.setRequestListId(stockPoDetail.getRequestListId());
        dto.setLastWarehouseId(stockPoDetail.getLastWarehouseId());
        dto.setStockPoQty(stockPoDetail.getStockPoQty());
        dto.setStockPoPrice(stockPoDetail.getStockPoPrice());
        dto.setStockPoRefPrice(stockPoDetail.getStockPoRefPrice());
        dto.setStockPoTotal(stockPoDetail.getStockPoTotal());
        dto.setTradeName(stockPoDetail.getTradeName());
        dto.setRemark(stockPoDetail.getRemark());
        dto.setStockPoItemTypeId(stockPoDetail.getStockPoItemTypeId());
        dto.setStockPoItemDiscount(stockPoDetail.getStockPoItemDiscount());
        dto.setStockPoItemMoneyDiscount(stockPoDetail.getStockPoItemMoneyDiscount());
        dto.setStockPoItemUnit(stockPoDetail.getStockPoItemUnit());
        dto.setStockPoTax(stockPoDetail.getStockPoTax());
        dto.setStockPoItemUnitcost(stockPoDetail.getStockPoItemUnitcost());
        dto.setStockPoItemOwner(stockPoDetail.getStockPoItemOwner());
        dto.setPoDetailCancel(stockPoDetail.getPoDetailCancel());
        dto.setStockPoBeforeDiscountPrice(stockPoDetail.getStockPoBeforeDiscountPrice());
        dto.setCancelReason(stockPoDetail.getCancelReason());
        dto.setStockDeliverQty(stockPoDetail.getStockDeliverQty());
        dto.setReferenceId(stockPoDetail.getReferenceId());
        dto.setStockItemUnitId(stockPoDetail.getStockItemUnitId());
        dto.setStockPackageQty(stockPoDetail.getStockPackageQty());
        dto.setStockPoTaxCost(stockPoDetail.getStockPoTaxCost());
        dto.setHosGuid(stockPoDetail.getHosGuid());
        dto.setStockPoLastPrice(stockPoDetail.getStockPoLastPrice());
        dto.setSupplierId(stockPoDetail.getSupplierId());
        dto.setItemDrugAccount(stockPoDetail.getItemDrugAccount());
        dto.setStockCoPoDetailId(stockPoDetail.getStockCoPoDetailId());
        dto.setRemainQty(stockPoDetail.getRemainQty());
        dto.setItemBarcode(stockPoDetail.getItemBarcode());
        dto.setSupplierItemId(stockPoDetail.getSupplierItemId());
        dto.setStockPkgBeforeDiscPrice(stockPoDetail.getStockPkgBeforeDiscPrice());
        dto.setStockPoItemMoneyDiscTot(stockPoDetail.getStockPoItemMoneyDiscTot());
        dto.setCheckKey(stockPoDetail.getCheckKey());
        dto.setRequestTagNo(stockPoDetail.getRequestTagNo());
        dto.setItemAvgCost(stockPoDetail.getItemAvgCost());
        dto.setStockPoItemDiscount2(stockPoDetail.getStockPoItemDiscount2());
        dto.setStockCostCenterId(stockPoDetail.getStockCostCenterId());
        dto.setStockIoNo(stockPoDetail.getStockIoNo());
        dto.setProjectRemark(stockPoDetail.getProjectRemark());
        dto.setStockAssetNo(stockPoDetail.getStockAssetNo());
        dto.setProjectNo(stockPoDetail.getProjectNo());
        dto.setWbs(stockPoDetail.getWbs());
        dto.setExchangeItemId(stockPoDetail.getExchangeItemId());
        dto.setExchangeItemUnitId(stockPoDetail.getExchangeItemUnitId());
        dto.setExchangeQty(stockPoDetail.getExchangeQty());
        dto.setExchangeRemainPackageQty(stockPoDetail.getExchangeRemainPackageQty());
        dto.setPoNormQty(stockPoDetail.getPoNormQty());
        dto.setPoNormStockItemUnitId(stockPoDetail.getPoNormStockItemUnitId());
        dto.setSapPrNo(stockPoDetail.getSapPrNo());
        dto.setStockBestowId(stockPoDetail.getStockBestowId());
        dto.setWhRemainQty(stockPoDetail.getWhRemainQty());
        dto.setDepRemainQty(stockPoDetail.getDepRemainQty());
        dto.setOtherDiscount(stockPoDetail.getOtherDiscount());
        dto.setStockPoPriceBeforeVat(stockPoDetail.getStockPoPriceBeforeVat());
        dto.setStockPoPcTypeId(stockPoDetail.getStockPoPcTypeId());
        dto.setStockVendorContractId(stockPoDetail.getStockVendorContractId());
        dto.setIsTransferUnit(stockPoDetail.getIsTransferUnit());
        dto.setBackOrderQty(stockPoDetail.getBackOrderQty());
        dto.setStockVendorContractItemId(stockPoDetail.getStockVendorContractItemId());
        return dto;
    }

    public StockPoDetail toEntity(StockPoDetailDto dto) {
        StockPoDetail stockPoDetail = new StockPoDetail();
        stockPoDetail.setStockPoDetailId(dto.getStockPoDetailId());
        stockPoDetail.setStockPoId(dto.getStockPoId());
        stockPoDetail.setItemId(dto.getItemId());
        stockPoDetail.setRequestListId(dto.getRequestListId());
        stockPoDetail.setLastWarehouseId(dto.getLastWarehouseId());
        stockPoDetail.setStockPoQty(dto.getStockPoQty());
        stockPoDetail.setStockPoPrice(dto.getStockPoPrice());
        stockPoDetail.setStockPoRefPrice(dto.getStockPoRefPrice());
        stockPoDetail.setStockPoTotal(dto.getStockPoTotal());
        stockPoDetail.setTradeName(dto.getTradeName());
        stockPoDetail.setRemark(dto.getRemark());
        stockPoDetail.setStockPoItemTypeId(dto.getStockPoItemTypeId());
        stockPoDetail.setStockPoItemDiscount(dto.getStockPoItemDiscount());
        stockPoDetail.setStockPoItemMoneyDiscount(dto.getStockPoItemMoneyDiscount());
        stockPoDetail.setStockPoItemUnit(dto.getStockPoItemUnit());
        stockPoDetail.setStockPoTax(dto.getStockPoTax());
        stockPoDetail.setStockPoItemUnitcost(dto.getStockPoItemUnitcost());
        stockPoDetail.setStockPoItemOwner(dto.getStockPoItemOwner());
        stockPoDetail.setPoDetailCancel(dto.getPoDetailCancel());
        stockPoDetail.setStockPoBeforeDiscountPrice(dto.getStockPoBeforeDiscountPrice());
        stockPoDetail.setCancelReason(dto.getCancelReason());
        stockPoDetail.setStockDeliverQty(dto.getStockDeliverQty());
        stockPoDetail.setReferenceId(dto.getReferenceId());
        stockPoDetail.setStockItemUnitId(dto.getStockItemUnitId());
        stockPoDetail.setStockPackageQty(dto.getStockPackageQty());
        stockPoDetail.setStockPoTaxCost(dto.getStockPoTaxCost());
        stockPoDetail.setHosGuid(dto.getHosGuid());
        stockPoDetail.setStockPoLastPrice(dto.getStockPoLastPrice());
        stockPoDetail.setSupplierId(dto.getSupplierId());
        stockPoDetail.setItemDrugAccount(dto.getItemDrugAccount());
        stockPoDetail.setStockCoPoDetailId(dto.getStockCoPoDetailId());
        stockPoDetail.setRemainQty(dto.getRemainQty());
        stockPoDetail.setItemBarcode(dto.getItemBarcode());
        stockPoDetail.setSupplierItemId(dto.getSupplierItemId());
        stockPoDetail.setStockPkgBeforeDiscPrice(dto.getStockPkgBeforeDiscPrice());
        stockPoDetail.setStockPoItemMoneyDiscTot(dto.getStockPoItemMoneyDiscTot());
        stockPoDetail.setCheckKey(dto.getCheckKey());
        stockPoDetail.setRequestTagNo(dto.getRequestTagNo());
        stockPoDetail.setItemAvgCost(dto.getItemAvgCost());
        stockPoDetail.setStockPoItemDiscount2(dto.getStockPoItemDiscount2());
        stockPoDetail.setStockCostCenterId(dto.getStockCostCenterId());
        stockPoDetail.setStockIoNo(dto.getStockIoNo());
        stockPoDetail.setProjectRemark(dto.getProjectRemark());
        stockPoDetail.setStockAssetNo(dto.getStockAssetNo());
        stockPoDetail.setProjectNo(dto.getProjectNo());
        stockPoDetail.setWbs(dto.getWbs());
        stockPoDetail.setExchangeItemId(dto.getExchangeItemId());
        stockPoDetail.setExchangeItemUnitId(dto.getExchangeItemUnitId());
        stockPoDetail.setExchangeQty(dto.getExchangeQty());
        stockPoDetail.setExchangeRemainPackageQty(dto.getExchangeRemainPackageQty());
        stockPoDetail.setPoNormQty(dto.getPoNormQty());
        stockPoDetail.setPoNormStockItemUnitId(dto.getPoNormStockItemUnitId());
        stockPoDetail.setSapPrNo(dto.getSapPrNo());
        stockPoDetail.setStockBestowId(dto.getStockBestowId());
        stockPoDetail.setWhRemainQty(dto.getWhRemainQty());
        stockPoDetail.setDepRemainQty(dto.getDepRemainQty());
        stockPoDetail.setOtherDiscount(dto.getOtherDiscount());
        stockPoDetail.setStockPoPriceBeforeVat(dto.getStockPoPriceBeforeVat());
        stockPoDetail.setStockPoPcTypeId(dto.getStockPoPcTypeId());
        stockPoDetail.setStockVendorContractId(dto.getStockVendorContractId());
        stockPoDetail.setIsTransferUnit(dto.getIsTransferUnit());
        stockPoDetail.setBackOrderQty(dto.getBackOrderQty());
        stockPoDetail.setStockVendorContractItemId(dto.getStockVendorContractItemId());
        return stockPoDetail;
    }
}
