spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: admin
  password: user1234

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D

spring:
  kafka:
    consumer:
      group-id: console-consumer-5182
<<<<<<< HEAD
      bootstrap-servers: 192.168.0.111:9092
=======
      bootstrap-servers: 172.27.133.90:9092
>>>>>>> 7ab337553934c54f8e90ce077e032f1f0ca2946c

line:
  bot:
    channel-token: dnDti4kzcgUR8oI3fUxQYJlZEwmRvvy4KzoAGUkj97V6gEjmpOT/IKchPlCFIdBE9KO9bXmbO1fhBNZR1mfBPZNH1Amz/YjHVXggZiQXyBAwDb2gF+Jj2VmN3+2kEHLWCWNXSq0kKJdghmNesnc3yQdB04t89/1O/w1cDnyilFU=
