import { StockItem } from "./stock-item";
import { StockPo } from "./stock-po";
import { StockRequestList } from "./stock-request-list";
import { StockWarehouse } from "./stock-warehouse";

export interface StockPoDetail {
    stockPoDetailId: string;
    stockPoId: StockPo;
    itemId: StockItem;
    requestListId: StockRequestList;
    lastWarehouseId: StockWarehouse;
    stockPoQty: number;
    stockPoPrice: number;
    stockPoRefPrice: number;
    stockPoTotal: number;
    tradeName: string;
    remark: string;
    stockPoItemTypeId: number;
    stockPoItemDiscount: number;
    stockPoItemMoneyDiscount: number;
    stockPoItemUnit: string;
    stockPoTax: boolean;
    stockPoItemUnitcost: number;
    stockPoItemOwner: string;
    poDetailCancel: boolean;
    stockPoBeforeDiscountPrice: number;
    cancelReason: string;
    stockDeliverQty: number;
    referenceId: number;
    stockItemUnitId: number;
    stockPackageQty: number;
    stockPoTaxCost: number;
    hosGuid: string;
    stockPoLastPrice: number;
    supplierId: number;
    itemDrugAccount: string;
    stockCoPoDetailId: number;
    remainQty: number;
    itemBarcode: string;
    supplierItemId: number;
    stockPkgBeforeDiscPrice: number;
    stockPoItemMoneyDiscTot: number;
    checkKey: string;
    requestTagNo: string;
    itemAvgCost: number;
    stockPoItemDiscount2: number;
    stockCostCenterId: number;
    stockIoNo: string;
    projectRemark: string;
    stockAssetNo: string;
    projectNo: string;
    wbs: string;
    exchangeItemId: number;
    exchangeItemUnitId: number;
    exchangeQty: number;
    exchangeRemainPackageQty: number;
    poNormQty: number;
    poNormStockItemUnitId: number;
    sapPrNo: string;
    stockBestowId: number;
    whRemainQty: number;
    depRemainQty: number;
    otherDiscount: number;
    stockPoPriceBeforeVat: number;
    stockPoPcTypeId: number;
    stockVendorContractId: number;
    isTransferUnit: boolean;
    backOrderQty: number;
    stockVendorContractItemId: number;
  }