export interface StockItem {
  itemId: number;
  itemName: string;
  itemUnit: string;
  itemType: number;
  itemUseStatus: 'Y' | 'N' | null; // หรือ boolean ถ้าแปลงแล้ว
  reorderLevel: number;
  reorderQty: number;
  unitCost: number;
  oldcode: string;
  fixDepartment: 'Y' | 'N' | null;
  stockItemCostTypeId: number;
  stockClassId: number;
  unitPrice: number;
  itemCode: string;
  stockItemRegdate: string; // ISO date string
  safetyStock: number;
  onhandQty: number;
  lastActiveDate: string;
  lastPoDate: string;
  itemCommonName: string;
  stockItemMtrId: number;
  stockItemAcctId: number;
  stockSubClassId: number;
  itemTradeName: string;
  stockItemNote: string;
  lastPoPrice: number;
  stockItemStdPrice: number;
  stockItemRefPrice: number;
  expireQty: number;
  supplierListText: string;
  vendorListText: string;
  poWaitQty: number;
  lastDeliverDate: string;
  itemMinQty: number;
  itemMaxQty: number;
  lastPoPrice1: number;
  lastStockVendorId: number;
  stockItemEdTypeId: number;
  lastCalcSiMap: string; // ISO datetime string
  updateDatetime: string;
  drugitemsNoSubstock: 'Y' | 'N' | null;
  itemStandardPrice: number;
  itemUnitQty: number;
  itemPackageName: string;
  icode: string;
  standardCode: string;
  dummyLeftQty: number;
  dummyLeftPrice: number;
  itemSubUnitQty: number;
  oldUnitCost: number;
  newcode: string;
  defaultDepartmentId: number;
  barcodeNumber: string;
  hosGuid: string;
  gpoCode: string;
  didstdCode: string;
  avgMonthUseQty: number;
  itemRegno: string;
  bdgNextyearPercent: number;
  itemNote: string;
  avgLeadDay: number;
  gpoVmi: 'Y' | 'N' | null;
  balanceQty: number;
  itemEng: string;
  itemTrand: string;
  itemTypeGroup: string;
  itemStatusControl: 'Y' | 'N' | null;
  itemVanType: 'Y' | 'N' | null;
  searchKeyword: string;
  abc: 'A' | 'B' | 'C' | null;
  vedCode: 'V' | 'E' | 'D' | null;
  pharmacologyGroup1: number;
  pharmacologyGroup2: number;
  pharmacologyGroup3: number;
  vatPercent: number;
  sapUnitName: string;
  sapItemName: string;
  sapUnitCost: number;
  sapActive: 'Y' | 'N' | null;
  manufacturerListText: string;
  useFixedAvgCost: 'Y' | 'N' | null;
  fixedAvgCost: number;
  stockMrpOrderTypeId: number;
  stockMrpLotSize: number;
  applyVat: 'Y' | 'N' | null;
  gpscCode: string;
}
