import { Officer } from "../types/officer";
import { StockBudget } from "./stock-budget";
import { StockDepartment } from "./stock-department";
import { StockPo } from "./stock-po";
import { StockPurchaseType } from "./stock-purchase-type";
import { StockWarehouse } from "./stock-warehouse";
export interface StockRequest {
  requestId: number;
  requestDate: string; // ISO Date string
  requestNo: string;
  requestReceiveDate: string;
  requestWarehouseId: StockWarehouse;
  requestComplete: "Y" | "N" | null;
  useDate: string;
  stockPoId: StockPo;
  hosGuid: string;
  budgetYear: number;
  stockSubject: string;
  stockSubjectPerson: string;
  supplierId: number;
  departmentId: StockDepartment;
  note: string;
  transportDay: number;
  budgetId: StockBudget;
  runNumber: number;
  numberYear: string;
  numberMonth: string;
  stockRequestDocId: string;
  projectId: number;
  stockUserApprove: Officer;
  stockApproveDate: string;
  stockUser: Officer;
  stockRequestDocumentId: string;
  projectPlanId: number;
  requestAllComplete: "Y" | "N" | null;
  budgetRunNo: number;
  approve: "Y" | "N" | null;
  requestTagNo: string;
  requestTime: string; // ISO time string e.g. "13:45:00"
  purchaseType: StockPurchaseType;
  stockBudgetTotal: number;
  stockBudgetUse: number;
  stockBudgetRemain: number;
  trimester: number;
  vatPercent: number;
  requestReason: string;
  requestTotalPrice: number;
  requestItemCount: number;
  stockBudgetPrUse: number;
  stockBudgetPrRemain: number;
  officerList: string;
  stockPoNoList: string;
  stockBudgetTypeId: number;
  depRequestNoList: string;
}
