import { StockItem } from "./stock-item";
import { StockRequest } from "./stock-request";

export interface StockRequestList {
  requestListId: number;
  requestId: StockRequest;
  itemId: StockItem;
  requestQty: number;
  requestLeftQty: number;
  requestUnit: string;
  requestListUnitPrice: number;
  requestListTotalPrice: number;
  requestComplete: 'Y' | 'N' | null; // หรือ boolean ถ้า backend แปลงแล้ว
  departmentId: number;
  requestDate: string; // ISO date string
  supplierId: number;
  remark: string;
  stockItemUnitId: number;
  stockPackageQty: number;
  hosGuid: string;
  incomingBalanceQty: number;
  rate1Month: number;
  stockItemUnitStandardPrice: number;
  packagePrice: number;
  lastPrice: number;
  approve: 'Y' | 'N' | null;
  useStockPlanBdg: 'Y' | 'N' | null;
  stockPlanTotalAmount: number;
  stockPlanRemainAmount: number;
  stockPlanOutgoingAmount: number;
  totalPrice: number;
  itemBarcode: string;
  unitQty: number;
  stockPoItemTypeId: number;
  stockRequestItemDiscount: number;
  stockRequestItemMoneyDiscount: number;
  rate3Month: number;
  tradeName: string;
  totalPlanQty: number;
  totalPoQty: number;
  planRemainQty: number;
  forcastMonth: number;
  stockVendorId: number;
  supplierItemId: number;
  stockDepRequestListId: number;
  stockPoPcTypeId: number;
  trimester: number;
  trimesterPlanQty: number;
  trimesterPlanAmount: number;
  trimesterPlanUseQty: number;
  trimesterPlanUseAmount: number;
  trimesterPlanRemainQty: number;
  trimesterPlanRemainAmount: number;
  vatPrice: number;
  totalPriceBeforeVat: number;
  lastWarehouseId: number;
  totalPlanAmount: number;
  itemFlag: 'Y' | 'N' | null;
  stockVendorContractId: number;
  contractRemainPackageQty: number;
}
