import { StockUser } from "./stock-user";
import { StockWareHouse } from "./stock-warehouse";

export interface StockRequest {
  requestId: string;
  requestDate: string;
  requestNo: string;
  requestReceiveDate: string;
  requestWarehouseId: StockWareHouse;
  requestComplete: boolean;
  useDate: string;
  stockPoId: string;
  hosGuid: string;
  budgetYear: number;
  stockSubject: string;
  stockSubjectPerson: string;
  supplierId: string;
  departmentId: string;
  note: string;
  transportDay: number;
  budgetId: string;
  runNumber: number;
  numberYear: number;
  numberMonth: number;
  stockRequestDocId: string;
  projectId: string;
  stockUserApprove: StockUser;
  stockApproveDate: string;
  stockUser: StockUser;
  stockRequestDocumentId: string;
  projectPlanId: string;
  requestAllComplete: boolean;
  budgetRunNo: string;
  approve: boolean;
  requestTagNo: string;
  requestTime: string;
  purchaseType: string;
  stockBudgetTotal: number;
  stockBudgetUse: number;
  stockBudgetRemain: number;
  trimester: number;
  vatPercent: number;
  requestReason: string;
  requestTotalPrice: number;
  requestItemCount: number;
  stockBudgetPrUse: number;
  stockBudgetPrRemain: number;
  officerList: string;
  stockPoNoList: string;
  stockBudgetTypeId: number;
  depRequestNoList: string;
}
