import { Metadata } from "next";

// ไม่ใช้ "use client" ในไฟล์นี้
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </>
  );
}
