import { StockWarehouse } from "./stock-warehouse";
import { StockRequest } from "./stock-request";
import { StockBudget } from "./stock-budget";
import { StockPurchaseType } from "./stock-purchase-type";

export interface StockPo {
  stockPoId: number;
  warehouseId: StockWarehouse;
  refRequestId: StockRequest;
  budgetId: StockBudget;
  stockPoNo: string;
  stockPoDate: string;
  supplierId: number;
  itemType: number;
  purchaseType: StockPurchaseType;
  paidStatusId: number;
  stockPoConfirm: 'Y' | 'N' | null;
  poAmount: number;
  poItemAmount: number;
  bdgYear: number;
  supplierAgentId: number;
  deliverCount: number;
  deliverComplete: 'Y' | 'N' | null;
  poTypeId: number;
  stockPoTax: 'Y' | 'N' | null;
  stockPoVat: number;
  stockPoDiscount: number;
  stockPoDiscountTotal: number;
  deliverCancel: 'Y' | 'N' | null;
  poCancel: 'Y' | 'N' | null;
  cancelReason: string;
  note: string;
  referenceId: number;
  deliveryRefDate: string;
  prRefNo: string;
  receiveWoPo: 'Y' | 'N' | null;
  entryStaff: string;
  authorizeStaff: string;
  entryDatetime: string;
  authorizeDatetime: string;
  hosGuid: string;
  deliverDay: number;
  stockCoPoTypeId: number;
  offerDate: string;
  chequeNo: string;
  chequeDate: string;
  paymentNo: string;
  endDate: string;
  transportDay: number;
  departmentId: number;
  stockUserId: number;
  stockBudgetUse: number;
  stockBudgetRemain: number;
  stockBudgetPrice: number;
  remark1: string;
  remark2: string;
  remark3: string;
  runnumber: number;
  numberYear: string;
  numberMonth: string;
  stockPoDocumentId: string;
  statusAppoveData: 'Y' | 'N' | null;
  significantNumber: string;
  isTemp: 'Y' | 'N' | null;
  requestTagNo: string;
  stockVendorId: number;
  stockPaidTypeId: number;
  stockPoDiscountAfterVat: number;
  stockPoVatAmount: number;
  poDocNo: string;
  stockPoRefId: number;
  stockVendorDiscTypeId: number;
  stockVendorDiscPercent: number;
  paidStatusUpdateDatetime: string;
  stockPoBeforeDiscountAmt: number;
  stockPoVendorDiscAmt: number;
  stockPoBeforeVatAmt: number;
  poDeliverRecvDate: string;
  poDeliverRecvTime: string;
  poDeliverInvStatTypeId: number;
  poDeliverGdStatTypeId: number;
  poDeliverConfirmTypeId: number;
  stockPoManualDiscAmt: number;
  stockPoAdjBeforeVat: number;
  poEstDate: string;
  stockPoPriorityTypeId: number;
  poEstDeliverDate: string;
  poContractNo: string;
  poDeliverAmount: number;
  deliverStop: 'Y' | 'N' | null;
  stockBudgetTransfer: number;
  stockVendorContractId: number;
  deliverStopDate: string;
  poApprovalDate: string;
  priceIncVat: 'Y' | 'N' | null;
  deliverNoList: string;
  egpProjectNo: string;
  egpControlNo: string;
  gfmisPoNo: string;
  requestNoList: string;
  stockBudgetTypeId: number;
  accPosted: 'Y' | 'N' | null;
  accPostedDatetime: string;
  stockDeliverDocNoList: string;
  roundTotalPrice: 'Y' | 'N' | null;
  useNoDiscount: 'Y' | 'N' | null;
  fineAmount: number;
  stockPoAdjVat: number;
}
