package com.example.workflow.dto;

import com.example.workflow.model.StockBudget;
import com.example.workflow.model.StockRequest;
import com.example.workflow.model.StockWarehouse;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class StockPoDto {
    private Long stockPoId;
    private StockWarehouse warehouseId;
    private StockRequest refRequestId;
    private StockBudget budgetId;
    private String stockPoNo;
    private LocalDate stockPoDate;
    private Long supplierId;
    private String itemType;
    private String purchaseType;
    private Long paidStatusId;
    private Character stockPoConfirm;
    private Double poAmount;
    private Integer poItemAmount;
    private Integer bdgYear;
    private Long supplierAgentId;
    private Integer deliverCount;
    private Character deliverComplete;
    private Long poTypeId;
    private Character stockPoTax;
    private Double stockPoVat;
    private Double stockPoDiscount;
    private Double stockPoDiscountTotal;
    private Character deliverCancel;
    private Character poCancel;
    private String cancelReason;
    private String note;
    private Long referenceId;
    private LocalDate deliveryRefDate;
    private String prRefNo;
    private Character receiveWoPo;
    private String entryStaff;
    private String authorizeStaff;
    private String entryDatetime;
    private String authorizeDatetime;
    private String hosGuid;
    private Integer deliverDay;
    private Long stockCoPoTypeId;
    private LocalDate offerDate;
    private String chequeNo;
    private LocalDate chequeDate;
    private String paymentNo;
    private LocalDate endDate;
    private String stockPoType;
    private Integer transportDay;
    private Long departmentId;
    private Long stockUserId;
    private Double stockBudgetUse;
    private Double stockBudgetRemain;
    private Double stockBudgetPrice;
    private String remark1;
    private String remark2;
    private String remark3;
    private Integer runnumber;
    private Integer numberYear;
    private Integer numberMonth;
    private Long stockPoDocumentId;
    private Character statusAppoveData;
    private String significantNumber;
    private Character isTemp;
    private String requestTagNo;
    private Long stockVendorId;
    private Long stockPaidTypeId;
    private Double stockPoDiscountAfterVat;
    private Double stockPoVatAmount;
    private String poDocNo;
    private Long stockPoRefId;
    private Long stockVendorDiscTypeId;
    private Double stockVendorDiscPercent;
    private LocalDateTime paidStatusUpdateDatetime;
    private Double stockPoBeforeDiscountAmt;
    private Double stockPoVendorDiscAmt;
    private Double stockPoBeforeVatAmt;
    private String poDeliverRecvDate;
    private String poDeliverRecvTime;
    private Long poDeliverInvStatTypeId;
    private Long poDeliverGdStatTypeId;
    private Long poDeliverConfirmTypeId;
    private Double stockPoManualDiscAmt;
    private Double stockPoAdjBeforeVat;
    private LocalDate poEstDate;
    private Long stockPoPriorityTypeId;
    private LocalDate poEstDeliverDate;
    private String poContractNo;
    private Double poDeliverAmount;
    private Character deliverStop;
    private Double stockBudgetTransfer;
    private Long stockVendorContractId;
    private String deliverStopDate;
    private String poApprovalDate;
    private Character priceIncVat;
    private String deliverNoList;
    private String egpProjectNo;
    private String egpControlNo;
    private String gfmisPoNo;
    private String requestNoList;
    private Long stockBudgetTypeId;
    private Character accPosted;
    private String accPostedDatetime;
    private String stockDeliverDocNoList;
    private Double roundTotalPrice;
    private Character useNoDiscount;
    private Double fineAmount;
    private Double stockPoAdjVat;
}
